"""Renders an approved OnboardingRequest into a real manifests/<app>.sh file —
the same shape a human writes by hand (see ../../manifests/full-stack-application.sh), so
nothing downstream (control-plane's on-disk allowlist, golden-build.sh,
strike.sh) needs to know this file was generated rather than hand-authored.

Every value is `shlex.quote`d, not just whitespace-guarded: a manifest is
`source`d as shell, and quoting with plain double quotes still lets `$(...)`
command substitution through. `shlex.quote` single-quotes anything with a
special character and leaves a bare safe token (e.g. `postgres`) untouched, so
the output still reads like a hand-written manifest — it just can't be turned
into a second command by a hostile field value.
"""

from __future__ import annotations

import shlex

from holodeck.onboarding.models import MANIFEST_FIELDS, OnboardingRequest

# rendered as a bash array, not a quoted string.
_ARRAY_FIELDS = {"HOLO_PORT_SERVICES"}
# rendered bare (no quoting) — genuinely numeric, never free text.
_NUMERIC_FIELDS = {"HOLO_APP_PORT"}


def render_manifest_sh(req: OnboardingRequest) -> str:
    lines = [
        "#!/usr/bin/env bash",
        f"# manifests/{req.app_name}.sh — generated by Holodeck's onboarding wizard,",
        f"# reviewed and approved by the Holodeck platform team before publish.",
        f"# Team: {req.team_slug} <{req.contact}> · request {req.request_id}",
        "# See docs/AUTOMATIC_ONBOARDING.md.",
        "",
        f"HOLO_APP={shlex.quote(req.app_name)}",
        "",
    ]
    if req.is_composite():
        # the entrypoint repo's checkout is what strike/finalize diff against
        # (manifests/README.md's HOLO_GIT_SUBDIR, only set for composites).
        entry = next((r for r in req.repos if r.role in ("app", "gateway")), req.repos[0])
        lines.append(f"HOLO_GIT_SUBDIR={shlex.quote(entry.name)}")
        lines.append("")
    for name in MANIFEST_FIELDS:
        f = req.manifest.get(name)
        value = f.value if f else None
        if name == "HOLO_APP_PORT" and value is None and req.preview_port:
            value = str(req.preview_port)
        if value is None:
            lines.append(f"{name}=  # TODO(team): not inferred — fill in before this app is struck")
        elif name in _ARRAY_FIELDS:
            lines.append(f"{name}=({' '.join(shlex.quote(v) for v in value.split())})")
        elif name in _NUMERIC_FIELDS:
            lines.append(f"{name}={int(value)}")
        else:
            lines.append(f"{name}={shlex.quote(value)}")

    # Emit per-repo test verification commands (Host Notary Exit 0 Gates)
    repo_cmds: list[str] = []
    for r in req.repos:
        if r.test_cmd:
            clean = r.name.replace("-", "_").replace(".", "_")
            lines.append(f"HOLO_TEST_CMD_{clean}={shlex.quote(r.test_cmd)}")
            repo_cmds.append(r.test_cmd)

    primary_test_cmd = req.test_cmd or (repo_cmds[0] if repo_cmds else None)
    if primary_test_cmd:
        lines.append(f': "${{HOLO_TEST_CMD:={shlex.quote(primary_test_cmd)}}}"')

    return "\n".join(lines) + "\n"
