#!/usr/bin/env bash
# strike.sh — strike an ephemeral workspace from the golden image.
#
# CoW-clones the golden, cuts a per-ticket branch, strips published ports for
# isolation, and warm-boots the stack against the CLONED, already-seeded
# pgdata. Proves the two load-bearing assumptions:
#   (1) COMPOSE_PROJECT_NAME fully isolates N stacks on one host
#   (2) Postgres comes up warm on a cloned pgdata (no reseed / migrate)
#
# App selection is via the manifest (HOLO_APP, default main):
#   ./strike.sh JSQ-118                              # main, isolated, no host ports
#   ./strike.sh JSQ-118 --preview 18018             # main, app on 0.0.0.0:18018
#   HOLO_APP=compliance ./strike.sh CPL-1 --preview 18081   # compliance hero
#
# With --preview it also verifies the app live: polls the readiness endpoint and
# runs the seeded-data proof query.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

TICKET=""; PREVIEW_PORT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --preview) PREVIEW_PORT="${2:?--preview needs a host port}"; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown flag: $1" ;;
    *) TICKET="$1" ;;
  esac; shift
done
[[ -n "$TICKET" ]] || die "usage: strike.sh <ticket> [--preview <hostPort>]"
[[ -d "$HOLO_GOLDEN" ]] || die "no golden image at $HOLO_GOLDEN — run the golden build for '$HOLO_APP' first"

id="$(holo_id "$TICKET")"; proj="ws-$id"; wsdir="$HOLO_WORKSPACES/$id"
[[ -e "$wsdir" ]] && die "workspace '$id' already exists at $wsdir — destroy it first"

log "[$proj] app=$HOLO_APP  CoW-cloning golden -> workspace..."
mkdir -p "$HOLO_WORKSPACES"
holo_cow_clone "$HOLO_GOLDEN" "$wsdir"

# Which directory actually gets the branch cut: a per-lease HOLO_TARGET_REPO (set by
# the control plane at acquire time, validated against the manifest's
# HOLO_COMPOSITE_REPOS) wins; otherwise fall back to the manifest's own static
# HOLO_GIT_SUBDIR (single-repo apps leave this empty and branch at $wsdir itself,
# unchanged from before target_repo existed).
subdir="${HOLO_TARGET_REPO:-${HOLO_GIT_SUBDIR:-}}"
git_root="$wsdir${subdir:+/$subdir}"
log "[$proj] cutting branch agent/$id in ${subdir:-<workspace root>}..."
# fetch, then branch from ORIGIN'S TIP, not from whatever commit the golden happened to
# freeze (a nightly-rebuilt golden can be up to a day stale). -B, not -b: idempotent on
# a retried ticket, matching the warm-pool claim path's same convention
# (providers/compose.py's _claim_slot). Every step here is best-effort with a fallback,
# never fatal — an offline box, a shallow clone with no origin/HEAD symref, or a repo
# with a genuinely unusual setup should still produce A workspace, just not necessarily
# branched from the freshest commit.
if git -C "$git_root" fetch --quiet origin 2>/dev/null; then
  default_branch="$(git -C "$git_root" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null)"
  default_branch="${default_branch#origin/}"
else
  warn "[$proj] git fetch failed in $git_root (offline?) — branching from the golden's HEAD as-is"
  default_branch=""
fi
if [[ -n "$default_branch" ]]; then
  git -C "$git_root" checkout -B "agent/$id" "origin/$default_branch" >/dev/null 2>&1 \
    || warn "branch agent/$id not created in $git_root (not a git repo, or another issue)"
else
  git -C "$git_root" checkout -B "agent/$id" >/dev/null 2>&1 \
    || warn "branch agent/$id not created in $git_root (not a git repo, or another issue)"
fi

# ---- isolation override: strip every published host port (remap the app if previewing) ----
ov="$wsdir/compose.ws.yaml"
{
  echo "# generated by strike.sh — per-workspace isolation. needs Compose >= 2.24 (!reset/!override)."
  echo "services:"
  for s in "${HOLO_PORT_SERVICES[@]}"; do
    if [[ "$s" == "$HOLO_APP_SERVICE" && -n "$PREVIEW_PORT" ]]; then
      # 0.0.0.0, not loopback: the POC box fronts workspaces with an internal ALB that
      # connects from the VPC. Safe only where ingress is already restricted (that box's
      # SG admits 10.91.0.0/16, no public inbound) — NOT on a laptop.
      echo "  $s: { ports: !override [\"0.0.0.0:${PREVIEW_PORT}:${HOLO_APP_PORT}\"] }"
    else
      echo "  $s: { ports: !reset [] }"
    fi
  done
} > "$ov"

# ---- compose file set: base + isolation (+ pgdata relocation for named-volume apps) ----
compose_files=(-f "$HOLO_COMPOSE_FILE" -f compose.ws.yaml)
[[ -n "$HOLO_PGDATA_OVERRIDE" ]] && compose_files+=(-f "$HOLO_DIR/$HOLO_PGDATA_OVERRIDE")
dc() { COMPOSE_PROJECT_NAME="$proj" FEATURE_FLAG_HOSTNAME="$proj" \
         docker compose "${compose_files[@]}" "$@"; }

log "[$proj] warm-booting services: ${WS_SERVICES:-<all>} ..."
cd "$wsdir"
dc up -d ${WS_SERVICES} \
  || die "[$proj] compose up failed — see: docker compose -p $proj logs"

# ---- assumption (2): Postgres warm on the clone ----
# Poll granularity is 0.25s, not 2s. The BUDGET is unchanged (90s) — attempts and
# sleep are scaled together on purpose: dropping the sleep alone would silently cut
# the timeout to 11s and turn a slow-but-healthy boot into a spurious failure.
# At 2s granularity a Postgres that came up at 3.1s wasn't noticed until 4.0s; that
# dead time was pure latency on every single strike.
log "[$proj] waiting for Postgres ($HOLO_PG_USER/$HOLO_PG_DB) on the cloned pgdata (no reseed)..."
ready=0
for _ in $(seq 1 360); do   # 360 * 0.25s = 90s, same budget as the old 45 * 2s
  if dc exec -T "$HOLO_PG_SERVICE" pg_isready -U "$HOLO_PG_USER" -d "$HOLO_PG_DB" >/dev/null 2>&1; then
    ready=1; break
  fi
  sleep 0.25
done
if [[ $ready -eq 1 ]]; then
  ok "[$proj] Postgres is warm — booted on the cloned seed, no reset. (assumption 2 ✓)"
else
  warn "[$proj] Postgres not ready after 90s — check: docker compose -p $proj logs $HOLO_PG_SERVICE"
fi

# ---- seeded-data proof (assumption 2, stronger: DB carries seeded rows) ----
seed_count="$(dc exec -T "$HOLO_PG_SERVICE" \
  psql -U "$HOLO_PG_USER" -d "$HOLO_PG_DB" -tAc "$HOLO_SEED_PROOF_SQL" 2>/dev/null | tr -d '[:space:]' || true)"
if [[ "${seed_count:-0}" =~ ^[0-9]+$ && "${seed_count:-0}" -gt 0 ]]; then
  ok "[$proj] seeded data present — ${HOLO_SEED_PROOF_SQL} -> $seed_count rows"
else
  warn "[$proj] seed proof empty/failed — ${HOLO_SEED_PROOF_SQL} -> '${seed_count}' (migrated+seeded golden?)"
fi

# ---- readiness (only when the app port is exposed) ----
# Scheme is manifest-driven (HOLO_READINESS_SCHEME): TLS entrypoints (main nginx:443,
# compliance-ui qong:8989) serve HTTPS with a self-signed cert, so a plain-HTTP poll
# used to print a false "not answering". For https we poll with -k.
if [[ -n "$PREVIEW_PORT" ]]; then
  ready_url="${HOLO_READINESS_SCHEME}://127.0.0.1:$PREVIEW_PORT$HOLO_READINESS_PATH"
  curl_ready=(curl -fsS); [[ "$HOLO_READINESS_SCHEME" == https ]] && curl_ready+=(-k)
  log "[$proj] polling app readiness at $ready_url ..."
  rz=""
  # Same 0.25s granularity / unchanged 60s budget as the Postgres gate above.
  for _ in $(seq 1 240); do   # 240 * 0.25s = 60s, same budget as the old 30 * 2s
    rz="$("${curl_ready[@]}" "$ready_url" 2>/dev/null || true)"
    [[ -n "$rz" ]] && break
    sleep 0.25
  done
  if [[ -n "$rz" ]]; then
    ok "[$proj] app is live — $HOLO_READINESS_PATH -> $rz"
  else
    warn "[$proj] $HOLO_READINESS_PATH not answering after 60s — check: docker compose -p $proj logs $HOLO_APP_SERVICE"
  fi
fi

echo
ok "[$proj] workspace up at $wsdir"
cat <<EOF
  exec in it:             docker compose -p $proj exec $HOLO_APP_SERVICE bash
  run a test:             docker compose -p $proj exec $HOLO_APP_SERVICE <test cmd>
${PREVIEW_PORT:+  preview the app:        ${HOLO_READINESS_SCHEME}://127.0.0.1:$PREVIEW_PORT$HOLO_READINESS_PATH}
  tear it down:           HOLO_APP=$HOLO_APP $SCRIPT_DIR/destroy.sh $TICKET
EOF
